name: Yayo amigo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build 
      - run: git config --global user.email "david._101@hotmail.com"
      - run: git config --global user.name "yayoamigo"
      - run: npm run deploy