name: Yayo amigo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git identity
        run: |
          git config --global user.email "david._101@hotmail.com"
          git config --global user.name "yayoamigo"
      - run: npm install
      - run: npm run build 
      - run: npm run deploy